### ISSUE TITLE
I just put one in here for Toolbar Oxygen

### ISSUE THREAD

**Issue by mrmjwilson** [deckerweb/toolbar-extras#3]
When I load both the Toolbars Extra (Eliminator) and then the Oxygen toolbar I get an error on line 801 of tbexob-settings.php Says must be 'Bool' or 'Boolean'

function ddw_tbexob_builder_logic_for_oxygen( bool $is_active ) {

	$default_builder = ddw_tbex_get_default_pagebuilder();

	/** Check for Oxygen Builder */
	if ( 'oxygen' === $default_builder && ! ddw_tbexob_is_oxygen_active() ) {
		return FALSE;
	}

	/** Default: return TRUE */
	return TRUE;

}  // end function

**Comment by deckerweb** [comment]
Please do not open new issues for the add-ons unless it is directly related to the base plugin.
The bug in the Oxygen add-on is related only to the add-on, thanks :-)
https://github.com/deckerweb/toolbar-extras-oxygen/issues/2
