### ISSUE TITLE
Plugin update icon is gone

### ISSUE THREAD

**Issue by acornavi** [deckerweb/toolbar-extras#4]
Hi,
I noticed that the usual plugin icon that showes the progress of plugins update is gone. All I can see is a little line or rather a dot.

Although, updates work but without this usual plugin notification it is hard to understand what is happening.

Best,
Ivan

**Comment by deckerweb** [comment]
@acornavi 
Hi and thanks for your feedback. Yes, this issue is already known and caused by CSS rule of my plugin. There will be a fix coming in the next version.

Sorry for the delay, though!

Also see #5 here

**Comment by deckerweb** [comment]
Issue was solved with the latest version 1.4.8, released a few hours ago :-)
