### ISSUE TITLE
Plugin Updates

### ISSUE THREAD

**Issue by grahamoz** [deckerweb/toolbar-extras#5]
Hi David,

Thanks for all your work on this great plugin.

I have found a problem on the Installed Plugins page I believe is caused by your plugin. I notice that when updating your plugin there appears 3 orange spinning update icons and then 3 green tick icons. So I assume your plugin is manipulating the interface somehow, as nearly all plugin updates only show 1 orange spinning icon.
The problem is that when updating any other plugins the static orange update icon disappears so that only the top single pixel line of the spinning icon is visible. When the update is finished only the top single pixel line is visible of the green tick. 
If I deactivate your plugin the other updates display correctly.

I have recorded a screencast video of the problem which is visible here -
https://drive.google.com/file/d/1z-7y4XRNZ0sMvCwPZGkVPY_l_yDbYscE/view

Thanks for your help,
Graham

**Comment by grahamoz** [comment]
I just realized that it is the top single pixel of the orange and green vertical lines next to the update icons.
Ta,
Graham

**Comment by deckerweb** [comment]
@grahamoz 
Hi and thanks for your feedback.
Yes, this is currently caused by my plugin from a CSS rule that "goes too far" and hides also other plugin's messages. Sorry for that.

There will be a fix in the next plugin version.

**Comment by grahamoz** [comment]
Thank you for the feedback.
I will be keen to the new version when it comes out.

Graham

**Comment by deckerweb** [comment]
Hi Graham,
this week I am on the go, and the new version will come out this weekend or early next week.
Thanks again for the heads up!

**Comment by deckerweb** [comment]
Issue was solved with the latest version 1.4.8, released a few hours ago :-)
