### ISSUE TITLE
Remove plugin group

### ISSUE THREAD

**Issue by lonix1** [deckerweb/toolbar-extras#8]
I already use [a plugin](https://wordpress.org/plugins/plugin-groups/) that categorizes my plugins.

But now there is another group "deckerweb" - how can I remove it?

**Comment by deckerweb** [comment]
@lonix1 
I have made you a code snippet which will remove this view/group.
See here: https://gist.github.com/deckerweb/40fd218ca51ae1d498709e28f40c44c2
(use code from line 5 onwards)

Recommended use is with Code Snippets plugin.

**Comment by lonix1** [comment]
Excellent! 👍
